[phases.setup]
aptPkgs = ["build-essential", "python3-dev", "libpq-dev"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x ./start.sh", "python manage.py collectstatic --noinput"]

[start]
cmd = "./start.sh"